remote_theme: "owasp/www--site-theme@main"
plugins:
 - jekyll-include-cache-0.2.0
 
# override default star and watch buttons
code_user: purpleteam-labs
code_repo: purpleteam

# core files/folders to exclude
exclude:
 - README.md
